### ISSUE TITLE
start的时候报错了，找了很久没找到解决方案，来请教一下

### ISSUE THREAD

**Issue by licoba** [zengxs/gitlab-arm64#59]
![image](https://github.com/zengxs/gitlab-arm64/assets/19327381/fa7c4c7c-171c-434b-b00e-ee615a23d345)

```
2023-12-07 14:27:21     ================================================================================
2023-12-07 14:27:21     Error executing action `create` on resource 'database_objects[postgresql]'
2023-12-07 14:27:21     ================================================================================
2023-12-07 14:27:21     
2023-12-07 14:27:21     RuntimeError
2023-12-07 14:27:21     ------------
2023-12-07 14:27:21     postgresql_user[gitlab] (postgresql::standalone line 21) had an error: RuntimeError: execute[create gitlab postgresql user] (postgresql::standalone line 13) had an error: RuntimeError: PostgreSQL did not respond before service checks were exhausted
2023-12-07 14:27:21     
2023-12-07 14:27:21     Cookbook Trace: (most recent call first)
2023-12-07 14:27:21     ----------------------------------------
2023-12-07 14:27:21     /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/libraries/helpers/pg_status_helper.rb:56:in `ready?'
2023-12-07 14:27:21     /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/libraries/helpers/base_pg_helper.rb:28:in `is_ready?'
2023-12-07 14:27:21     /opt/gitlab/embedded/cookbooks/cache/cookbooks/postgresql/resources/user.rb:16:in `block (3 levels) in class_from_file'
2023-12-07 14:27:21     /opt/gitlab/embedded/cookbooks/cache/cookbooks/postgresql/resources/user.rb:13:in `block in class_from_file'
2023-12-07 14:27:21     /opt/gitlab/embedded/cookbooks/cache/cookbooks/gitlab/resources/database_objects.rb:21:in `block in class_from_file'
2023-12-07 14:27:21     
```

**Comment by licoba** [comment]
问题找到了，Google了几个小时，换了几个国家的VPN，终于找到答案了，docker的原因，勾选这个之后重启docker
https://github.com/sameersbn/docker-gitlab/issues/2818
![image](https://github.com/zengxs/gitlab-arm64/assets/19327381/c29b60b0-a4a2-4821-afcb-37275c1dd4cd)
